### ISSUE TITLE
Deck building with reprinted cards

### ISSUE THREAD

**Issue by mlogie** [fafranco82/swdestinydb-json-data#176]
When deckbuilding at the moment, you can't see cards which have been reprinted in the deckbuilder (for instance if you're building a deck and want to add a character and show only convergence cards, first order stormtrooper doesn't appear).  I'm guessing this is a minor bug that will sort itself out upon rotation, but is there a way round it?

**Comment by fafranco82** [comment]
Yes, reprinted cards with set filters are not working right now, it's a known bug I must fix when I have time :(

**Comment by mlogie** [comment]
it would appear that you fixed this, so I'm closing this issue
