### ISSUE TITLE
Laat cost

### ISSUE THREAD

**Issue by mlogie** [fafranco82/swdestinydb-json-data#177]
@fafranco82 the cost of the LAAT gunship on the web is showing as 1, but it definitely says 4 (which is correct) in the JSON. Can't work out why. Any chance you could have a look?

**Comment by fafranco82** [comment]
In my files it has cost 1... maybe it was an error resolving conflicts when I merged from 2 differents PR :(

It is now fixed. Remember to pull changes from upstream :)

**Comment by fafranco82** [comment]
It seems I forgot to upload last merged files ^^ It is right now.
