### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by mlogie** [fafranco82/swdestinydb-json-data#179]
@fafranco82 when is rotation going to happen on the web, and is there anything I can do to help make it happen?  Convergence launched today (though I guess it isn't legal for 11 days)

**Comment by fafranco82** [comment]
I've just "released" Convergence :)

**Comment by mlogie** [comment]
Woop woop, nice one.  Great work, loving deck building with the new set.  Thanks, as always, for all your work on this website.
