### ISSUE TITLE
Incorrect images

### ISSUE THREAD

**Issue by mlogie** [fafranco82/swdestinydb-json-data#262]
At the moment, all the images from Fives (5C) downwards are wrong.  I think this is because in the image set there are three copies of Send In the Troopers, but there's actually only one instance of this card in reality, it just has 3 possible reverse sides. 
 So the images for Fives (5C) and Woolfe (5D) need to be added in, and all the other images shunted up by 4.

**Comment by lfgcampos** [comment]
@mlogie sorry to reuse the issue but it sounded generic enough.
There are images missing on CONV as well (I believe 18), ex: https://swdestinydb.com/card/09057

I can provide you the name of the missing ones if needed.

**Comment by fafranco82** [comment]
Images for Transformations are fixed now.

CONV18 was part of the starters sets... I don't know why, but the last time I see it were not uploaded in CardGameDB :S
