### ISSUE TITLE
Inclusion of ban list

### ISSUE THREAD

**Issue by mlogie** [fafranco82/swdestinydb-json-data#283]
Two recent changes to the holocron don't work in the current schema.  This is for one item:
There is now a ban list.  I don't know how to implement this on the site.  I thought it probably should be added as an extra element to the format schema, which I'm happy to add, but I wasn't sure whether this would break something else.
Any thoughts @fafranco82 ?

**Comment by fafranco82** [comment]
First is adding to the `formats.json` a field `banned`, similar to `restricted`, this must be easy. The other part of the work must be done in [fafranco82/swdestinydb](https://github.com/fafranco82/swdestinydb) repo

**Comment by mlogie** [comment]
I'll do step 1 and add it to my pull request

**Comment by mlogie** [comment]
Good work, I see this is fixed
