### ISSUE TITLE
New restricted pairings list

### ISSUE THREAD

**Issue by mlogie** [fafranco82/swdestinydb-json-data#284]
The next update to the holocron:
The restricted list has been replaced in ARH Standard with a restricted pairings.  Meaning there are now multiple pairings of cards which cannot be combined e.g. card A cannot be combined with card B, card C cannot be combined with card D, but card A can be combined with cards C and D.  This means that the old implementation of the restricted list doesn't work.  I have no idea where to start on this one @fafranco82 , sorry

**Comment by mlogie** [comment]
I'm happy to add all the card codes if you're able to implement this in the schema somehow?

**Comment by fafranco82** [comment]
But... the old "only 1 card from restricted list" still exists for other formats, right?

As with #283, adding it to `formats.json` may be easy, but in this case is a little bit more tricky. There are several ways to do this:

- For every card, indicates with which other card cannot be in the same deck
- List every possible pair

Both of them are verbose and redundant. For example, if A cannot be combined with B and C, the first approach will look like something similar to this:
```
restrictedCombinations: {
  "A": ["B", "C"],
  "B": ["A"],
  "C": ["B"]
}
```

And with the second one:
```
restrictedCombinations: [ ["A", "B"], ["A", "C"] ]
```

The first one is more verbose, but quickier to use it later to verify a valid deck. The second one it's faster to write, but it needs more pre-processing when validating the deck.

Which one do you prefer?

**Comment by mlogie** [comment]
I like verbose.  And if it's easier for you, great.  I'm a little confused about your implementation though, as I don't think what you've written is the same as in my example.
I think I need to do this:
restrictedCombinations: {
  "A": ["B"],
  "B": ["A"],
  "C": ["D"],
  "D": ["C"]
}

right?

**Comment by mlogie** [comment]
I'll add restrictedCombinations and the relevant codes to the version too

**Comment by mlogie** [comment]
And yes, restricted is the same for previous formats

**Comment by fafranco82** [comment]
> I like verbose. And if it's easier for you, great. I'm a little confused about your implementation though, as I don't think what you've written is the same as in my example.
> I think I need to do this:
> restrictedCombinations: {
> "A": ["B"],
> "B": ["A"],
> "C": ["D"],
> "D": ["C"]
> }
> 
> right?

This way you cannot have more than one restriction with the same card (look at my examples, there are two restricted pairs with card A in common, A-B and A-C)

**Comment by fafranco82** [comment]
I guess it's somehing possible in the future if it's not happening yet

**Comment by mlogie** [comment]
OK - I think I misunderstood.  Are you replacing restricted with restrictedCombinations?  So what you wrote would replace the old restriction of cards A, B and C?
I was trying to write this up that it banned A-B, banned C-D, but that A-C, A-D, B-C, B-D, C-A, C-B, D-A and D-B are still allowed.

**Comment by mlogie** [comment]
And the restricted pairings is current standard.  It got implemented a few weeks ago but I've only just got around to thinking about it

**Comment by fafranco82** [comment]
No, nor replacing it. That's why I named it differently. My examples are new data to add. I only add the possibility that A-C can be also banned along with A-B and C-D

**Comment by mlogie** [comment]
Just re-read your comment properly.  Yes, sorry, that was my fauly for misunderstanding.  So, do you want to replace restricted with restrictedCombinations, so that, say, an old restricted list looks like this:
restrictedCombinations: {
  "A": ["B", "C", "D", "E"],
  "B": ["A", "C", "D", "E"],
  "C": ["A", "B", "D", "E"],
  "D": ["A", "B", "C", "D"],
}
?

**Comment by mlogie** [comment]
Excellent, thank you.  Sorry for being slow

**Comment by mlogie** [comment]
Thanks for merging my changes.  It looks like the ban list is working but the restricted pairings are not showing up though.
On another matter - I love what you've done with elite non-unique characters.  That is a great fix - thank you @fafranco82

**Comment by fafranco82** [comment]
This is only data. I need to show that info on the web (you can see the web source code on https://github.com/fafranco82/swdestinydb).

I create an issue there: fafranco82/swdestinydb#326 to remember it.

Also note that I changed ´restrictedCombinations` for `restrictedPairs`, shorter and sounds better XD

**Comment by mlogie** [comment]
Good work, thank you 👍
