### ISSUE TITLE
Flip cards

### ISSUE THREAD

**Issue by mlogie** [fafranco82/swdestinydb-json-data#307]
Hi @fafranco82.  A while ago I added a new flag to cards in the db: "flip_card".  The idea was that I could then alter the java bit of the code so that it would look for this flag when building jsons for tts export.  However, my lack of java knowledge is failing me.
Would you be able to have a look?  There's 3 occassions in the tts.json.twig where it says:
{% if slot.card.set.code == "TR" %}
Then sets "BackIsHidden" and "UniqueBack" accordingly.
I felt like you could replace each of these with something like this:
{% if slot.card.set.code == "TR"|slot.card.flip.card == true %}
But I guess there's a little more to it than that.  Are you able to have a look?  Hopefully it's just a few lines of code and would mean that flip cards will spawn correctly now, and in the future, just by adding this flip_card flag to all future flip cards.
Thank you.

**Comment by fafranco82** [comment]
Done :)

**Comment by mlogie** [comment]
Closing this one, as it's done
