### ISSUE TITLE
TTS IDs not exporting correctly

### ISSUE THREAD

**Issue by mlogie** [fafranco82/swdestinydb-json-data#335]
Hi @fafranco82 
First off, thanks for all the updates lately.
I submitted a fix to the TTS IDs a couple of days ago, and though they've been accepted, the IDs don't seem to be exporting correctly still. Is it possible that the old IDs (I incorrectly submitted) are still being used for some cards? Is it possible to do a reset or something, so that the website picks up the correct IDs from HS.json. Specifically it's the second half of the set which is exporting incorrect IDs (cards 70+). Thanks,
Mark

**Comment by fafranco82** [comment]
Was my fault... I forgot to confirm changes to the database U_U Sorry. They're changed now.

**Comment by mlogie** [comment]
Nice one, thanks
