### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by ss2art** [fafranco82/swdestinydb-json-data#54]
A couple of Typos I have found

Spirit of Rebellion Card 68 **We Have Them Now** 

> Play only if you control **de** battlefield.

Empire at War Card 50 **Psychometry**

> Draw cards equal to the **avlue**

**Comment by fafranco82** [comment]
Thanks!

**Comment by ss2art** [comment]
Also
Two Player Game Card 19 **Your _Skill_ Are Complete** ,  should read **_Skills_**

**Comment by fafranco82** [comment]
Thanks again :)
