### ISSUE TITLE
My json file doesn't merge

### ISSUE THREAD

**Issue by KlarkD** [fafranco82/swdestinydb-json-data#72]
[EaW.zip](https://github.com/fafranco82/swdestinydb-json-data/files/1461865/EaW.zip)
Hi everyone.
I had some issues with my json file about the ITA translation of EaW set. I think it could have some syntax errors: i examined the file few times and cannot find more. Can someone help me correct it? I understood you use some tool to validate files...

**Comment by fafranco82** [comment]
I use the python script `validate.py` (in the README you can find how to use it and what dependecies it needs). But the validator only checks set files if the set is in the translated `sets.json` file, so it didn't throw up any errors for ìt/set/EaW.json' file :(

I've just added EaW set name translation in `it/sets.json` (taking the translated name from Asmodee Italia page) and `validate.py` now states that `EaW.json` JSON is not valid. I use Sublime Text to edit these files, with a plugin for JSON that, among other things, includes JSON validation... Two errors were found: a missing comma after a line, and a incompleted new line character (`\n`), with only the backlash, making `\O` (`O` was the following character of newline) an invalid character.

Now is all fixed and merged, anyway ;) Thanks for your work!!

**Comment by KlarkD** [comment]
Wonderful tip, franco! This tool really helps: i found those 2 errors in a matter of seconds after installing ST and its json plugin. Thanks a lot!
