### ISSUE TITLE
Crystal Ball and Force Rend images are swapped

### ISSUE THREAD

**Issue by joemasilotti** [fafranco82/swdestinydb-json-data#88]
How are the images populated? Happy to submit a PR, just not sure where to make the changes.

**Comment by fafranco82** [comment]
The images are populated from a repo in bitbucket. If you wish I can give you permission ;) 

Thanks for the report!

**Comment by fafranco82** [comment]
Well, I've just noticed that info was swapped, images are ok, hahahaha

**Comment by joemasilotti** [comment]
Ha, nice! Glad it’s fixed. 

And yeah, I would love access. I also would love to chat more about how I can help out with the repos. Shoot me an email at joe@masilotti.com if you could use another hand!
